name: Update Charts

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: contains( github.event.head_commit.message, 'Update dependency gchq/CyberChef' )
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Extract version
        id: extract_version
        run: |
          sed -nE 's/ARG CYBERCHEF_VERSION="(.*)"/::set-output name=version::\1/p' Dockerfile

      - name: Update Chart.yaml
        run: |
          sed -Ei \
            -e 's/^(version\:) .*/\1 '${{ steps.extract_version.outputs.version }}'/g' \
            -e 's/^(appVersion\:) .*/\1 "'${{ steps.extract_version.outputs.version }}'"/g' \
            charts/cyberchef/Chart.yaml

      - name: Commit changes
        run: |
          git commit -am 'update chart to ${{ steps.extract_version.outputs.version }}'
          git push
