name: Docker Build and Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: "Container version to build"
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: "Container version to build"
        required: true
        type: string
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.event.inputs.version && github.event.inputs.version || github.ref_name }}

jobs:
  build-and-push:
    name: Build and Push Docker Image

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "${{ env.TAG }}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}},value=${{ env.TAG }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
